
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const HAVE_MIGRATION = "HAVE_MIGRATION"
export const RESTORE_TOKEN = "RESTORE_TOKEN"
export const USER_LOGOUT = "USER_LOGOUT"
export const SAVE_USER = "SAVE_USER"
